//! Phosphor icons for Celestia desktop — drawn on raw `gpui`.
//!
//! The upstream `gpui-phosphor` crate targets the `gpui` 0.2 lineage, so the
//! Phosphor Core SVGs are vendored under `assets/phosphor/` and the typed
//! [`PhosphorIcon`] catalog is generated by this crate's build script instead.
//! Three single-color weights are embedded — regular, bold, fill; duotone is
//! skipped because GPUI's SVG renderer paints every path with one color, and
//! the weight lives in the asset path (`phosphor/<weight>/<name>.svg`).
//!
//! Rendering is a plain [`gpui::svg`] — no third-party icon component sits in
//! between. Two ways in:
//!
//! - Bare `.child(PhosphorIcon::Heart)` renders at the surrounding text style
//!   at the regular weight (the generated `RenderOnce` impl).
//! - [`Phosphor`] selects a weight, and optionally size / colour / rotation,
//!   inheriting the surrounding text style otherwise — the counterpart of
//!   gpui-phosphor's `Icon` builder.

use gpui::{
    App, Hsla, IntoElement, Pixels, Radians, RenderOnce, SharedString, Styled as _, Transformation,
    Window, svg,
};

include!(concat!(env!("OUT_DIR"), "/phosphor_icon.rs"));

/// Version of the embedded Phosphor Core release.
pub const PHOSPHOR_VERSION: &str = "2.1.1";

/// Stroke/fill weight of a Phosphor icon. Only weights vendored under
/// `assets/phosphor/` are listed; [`PhosphorWeight::path`] then always
/// resolves.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub enum PhosphorWeight {
    /// Outlined 16px-grid stroke — the Phosphor default.
    #[default]
    Regular,
    /// Heavier outline stroke.
    Bold,
    /// Solid fill.
    Fill,
}

impl PhosphorWeight {
    /// Asset directory under `phosphor/` for this weight.
    pub fn dir(self) -> &'static str {
        match self {
            Self::Regular => "regular",
            Self::Bold => "bold",
            Self::Fill => "fill",
        }
    }

    /// Asset path for `icon` at this weight.
    pub fn path(self, icon: PhosphorIcon) -> SharedString {
        format!("phosphor/{}/{}.svg", self.dir(), icon.name()).into()
    }
}

/// A weight-aware Phosphor icon that inherits the surrounding text style
/// (size and color) unless overridden.
#[derive(IntoElement)]
pub struct Phosphor {
    icon: PhosphorIcon,
    weight: PhosphorWeight,
    size: Option<Pixels>,
    color: Option<Hsla>,
    rotation: Option<Radians>,
}

impl Phosphor {
    pub fn new(icon: PhosphorIcon) -> Self {
        Self {
            icon,
            weight: PhosphorWeight::default(),
            size: None,
            color: None,
            rotation: None,
        }
    }

    /// Stroke/fill weight (asset prefix); defaults to [`PhosphorWeight::Regular`].
    pub fn weight(mut self, weight: PhosphorWeight) -> Self {
        self.weight = weight;
        self
    }

    /// Explicit pixel size; defaults to the surrounding text size.
    pub fn size(mut self, size: impl Into<Pixels>) -> Self {
        self.size = Some(size.into());
        self
    }

    /// Explicit color; defaults to the surrounding text color.
    pub fn color(mut self, color: impl Into<Hsla>) -> Self {
        self.color = Some(color.into());
        self
    }

    /// Rotation about the icon's centre, in radians.
    ///
    /// GPUI gives no element transform, so this rides on the SVG's own
    /// `Transformation` — it is the only way to spin a glyph. Pair it with
    /// [`gpui::AnimationExt::with_animation`] for a running spinner.
    pub fn rotation(mut self, radians: impl Into<Radians>) -> Self {
        self.rotation = Some(radians.into());
        self
    }
}

impl RenderOnce for Phosphor {
    fn render(self, window: &mut Window, _: &mut App) -> impl IntoElement {
        let text_style = window.text_style();
        let size = self
            .size
            .unwrap_or_else(|| text_style.font_size.to_pixels(window.rem_size()));
        let color = self.color.unwrap_or(text_style.color);

        let icon = svg()
            .path(self.weight.path(self.icon))
            .flex_shrink_0()
            .text_color(color)
            .size(size);

        match self.rotation {
            Some(rotation) => icon.with_transformation(Transformation::rotate(rotation)),
            None => icon,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn count_matches_all() {
        assert_eq!(PhosphorIcon::ALL.len(), PhosphorIcon::COUNT);
        const { assert!(PhosphorIcon::COUNT > 1_000) };
    }

    #[test]
    fn names_are_unique_kebab_stems() {
        let mut seen = std::collections::BTreeSet::new();
        for icon in PhosphorIcon::ALL {
            let name = icon.name();
            assert!(!name.is_empty());
            assert!(name.chars().all(|c| c.is_ascii_lowercase() || c == '-'));
            assert!(seen.insert(name), "duplicate name: {name}");
        }
    }

    #[test]
    fn bare_icon_renders_at_the_regular_weight() {
        assert_eq!(
            PhosphorWeight::Regular.path(PhosphorIcon::Heart).as_ref(),
            "phosphor/regular/heart.svg"
        );
    }

    #[test]
    fn weight_paths_use_the_weight_directory() {
        assert_eq!(
            PhosphorWeight::Regular
                .path(PhosphorIcon::PaperPlaneTilt)
                .as_ref(),
            "phosphor/regular/paper-plane-tilt.svg"
        );
        assert_eq!(
            PhosphorWeight::Bold
                .path(PhosphorIcon::PaperPlaneTilt)
                .as_ref(),
            "phosphor/bold/paper-plane-tilt.svg"
        );
        assert_eq!(
            PhosphorWeight::Fill
                .path(PhosphorIcon::PaperPlaneTilt)
                .as_ref(),
            "phosphor/fill/paper-plane-tilt.svg"
        );
    }
}
