//! Generates the typed Phosphor icon catalog from the SVGs vendored under
//! `assets/phosphor/{weight}/` — the same approach gpui-phosphor uses, but
//! targeting gpui-kit's `IconNamed` so the glyphs plug into gpui-kit's `Icon`.

use std::{
    collections::{BTreeMap, BTreeSet},
    env, fmt::Write as _,
    fs,
    path::PathBuf,
};

/// Weights vendored under `assets/phosphor`. Keep in sync with
/// `PhosphorWeight` in `src/components/icon.rs`.
const WEIGHTS: [&str; 3] = ["regular", "bold", "fill"];

fn main() {
    println!("cargo:rerun-if-changed=assets/phosphor");

    // kebab-case file stem -> PascalCase variant; every weight must carry the
    // exact same set of names so weight only ever changes the path prefix.
    let mut variants: BTreeMap<String, String> = BTreeMap::new();
    let mut per_weight: BTreeMap<&str, BTreeSet<String>> =
        WEIGHTS.iter().map(|w| (*w, BTreeSet::new())).collect();

    for weight in WEIGHTS {
        let dir = PathBuf::from("assets/phosphor").join(weight);
        for entry in fs::read_dir(&dir).unwrap_or_else(|err| panic!("{}: {err}", dir.display())) {
            let path = entry.expect("read phosphor asset directory entry").path();
            if path.extension().and_then(|ext| ext.to_str()) != Some("svg") {
                continue;
            }
            let stem = path
                .file_stem()
                .and_then(|stem| stem.to_str())
                .expect("UTF-8 phosphor icon name")
                .to_owned();
            let variant = pascal_case(&stem);
            if let Some(existing) = variants.get(&variant) {
                assert_eq!(
                    existing, &stem,
                    "duplicate phosphor icon variant: {variant} from multiple stems ({existing} and {stem})"
                );
            } else {
                variants.insert(variant.clone(), stem.clone());
            }
            per_weight
                .get_mut(weight)
                .expect("known weight")
                .insert(stem);
        }
    }

    let sets: Vec<&BTreeSet<String>> = per_weight.values().collect();
    for pair in sets.windows(2) {
        assert_eq!(
            pair[0], pair[1],
            "phosphor weight directories disagree; every weight must ship the same icon set"
        );
    }
    assert!(!variants.is_empty(), "no phosphor icons found");

    let mut code = String::new();
    writeln!(
        code,
        "// @generated by build.rs from assets/phosphor — do not edit."
    )
    .unwrap();
    writeln!(
        code,
        "/// Typed catalog of the vendored Phosphor icons (Core {} — {} glyphs per weight).",
        phospor_version(),
        variants.len()
    )
    .unwrap();
    writeln!(
        code,
        "#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, ::gpui_kit::IntoElement)]"
    )
    .unwrap();
    writeln!(code, "pub enum PhosphorIcon {{").unwrap();
    for variant in variants.keys() {
        writeln!(code, "    {variant},").unwrap();
    }
    writeln!(code, "}}").unwrap();

    writeln!(code, "impl PhosphorIcon {{").unwrap();
    writeln!(code, "    /// Every icon, alphabetical by file name.").unwrap();
    writeln!(code, "    pub const ALL: &'static [Self] = &[").unwrap();
    for variant in variants.keys() {
        writeln!(code, "        Self::{variant},").unwrap();
    }
    writeln!(code, "    ];").unwrap();
    writeln!(
        code,
        "    /// Number of distinct glyphs (same for every weight)."
    )
    .unwrap();
    writeln!(code, "    pub const COUNT: usize = {};", variants.len()).unwrap();
    writeln!(
        code,
        "    /// The kebab-case Phosphor file name (`\"paper-plane-tilt\"`)."
    )
    .unwrap();
    writeln!(code, "    pub fn name(self) -> &'static str {{").unwrap();
    writeln!(code, "        match self {{").unwrap();
    for (variant, stem) in &variants {
        writeln!(code, "            Self::{variant} => {stem:?},").unwrap();
    }
    writeln!(code, "        }}").unwrap();
    writeln!(code, "    }}").unwrap();
    writeln!(code, "}}").unwrap();

    // Regular is the default weight: `Icon::new(PhosphorIcon::Heart)` resolves
    // without any wrapper.
    writeln!(
        code,
        "impl ::gpui_kit::assets::IconNamed for PhosphorIcon {{"
    )
    .unwrap();
    writeln!(
        code,
        "    fn path(self) -> ::gpui_kit::SharedString {{"
    )
    .unwrap();
    writeln!(code, "        match self {{").unwrap();
    for (variant, stem) in &variants {
        writeln!(
            code,
            "            Self::{variant} => \"phosphor/regular/{stem}.svg\","
        )
        .unwrap();
    }
    writeln!(code, "        }}.into()").unwrap();
    writeln!(code, "    }}").unwrap();
    writeln!(code, "}}").unwrap();

    // `.child(PhosphorIcon::Heart)` renders at the surrounding text style,
    // mirroring `gpui_kit::assets::IconName`.
    writeln!(
        code,
        "impl ::gpui_kit::RenderOnce for PhosphorIcon {{"
    )
    .unwrap();
    writeln!(
        code,
        "    fn render(self, _: &mut ::gpui_kit::Window, _: &mut ::gpui_kit::App) -> impl ::gpui_kit::IntoElement {{"
    )
    .unwrap();
    writeln!(code, "        ::gpui_kit::component::Icon::new(self)").unwrap();
    writeln!(code, "    }}").unwrap();
    writeln!(code, "}}").unwrap();

    writeln!(
        code,
        "impl From<PhosphorIcon> for ::gpui_kit::AnyElement {{"
    )
    .unwrap();
    writeln!(code, "    fn from(icon: PhosphorIcon) -> Self {{").unwrap();
    writeln!(code, "        icon.into_any_element()").unwrap();
    writeln!(code, "    }}").unwrap();
    writeln!(code, "}}").unwrap();

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("phosphor_icon.rs"), code).expect("write phosphor_icon.rs");
}

/// `paper-plane-tilt` -> `PaperPlaneTilt`, matching gpui-kit-assets' variant
/// naming so the two catalogs read the same.
fn pascal_case(stem: &str) -> String {
    stem.split(['-', '_', '.'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            let first = chars.next().expect("non-empty part");
            format!("{}{}", first.to_ascii_uppercase(), chars.as_str())
        })
        .collect()
}

/// Version of the embedded Phosphor Core release, surfaced as
/// [`crate::components::icon::PHOSPHOR_VERSION`].
fn phospor_version() -> &'static str {
    "2.1.1"
}
