//! Phosphor icons for Celestia desktop — the gpui-phosphor approach ported to
//! the gpui-kit stack.
//!
//! The upstream `gpui-phosphor` crate targets the `gpui` 0.2 lineage and can't
//! be linked against gpui-kit's `gpui-pre` types, so the Phosphor Core SVGs
//! are vendored under `assets/phosphor/` and the typed [`PhosphorIcon`]
//! catalog is generated by this crate's build script instead. Three
//! single-color weights are embedded — regular, bold, fill; duotone is
//! skipped because GPUI's SVG renderer paints every path with one color, and
//! the weight lives in the asset path (`phosphor/<weight>/<name>.svg`).
//!
//! Two ways to render:
//!
//! - Any [`PhosphorIcon`] implements gpui-kit's `IconNamed`, so it plugs
//!   straight into gpui-kit's `Icon` at the regular weight:
//!   `Icon::new(PhosphorIcon::Heart)`. Bare `.child(PhosphorIcon::Heart)`
//!   works too and inherits the surrounding text style.
//! - [`Phosphor`] selects a weight explicitly and inherits size/color from
//!   the surrounding text style unless overridden — the counterpart of
//!   gpui-phosphor's `Icon` builder.

use gpui_kit::component::{Icon, Sizable as _};
use gpui_kit::{App, Hsla, IntoElement, Pixels, RenderOnce, SharedString, Styled as _, Window};

include!(concat!(env!("OUT_DIR"), "/phosphor_icon.rs"));

/// Version of the embedded Phosphor Core release.
pub const PHOSPHOR_VERSION: &str = "2.1.1";

/// Stroke/fill weight of a Phosphor icon. Only weights vendored under
/// `assets/phosphor/` are listed; [`PhosphorWeight::path`] then always
/// resolves.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub enum PhosphorWeight {
    /// Outlined 16px-grid stroke — the Phosphor default.
    #[default]
    Regular,
    /// Heavier outline stroke.
    Bold,
    /// Solid fill.
    Fill,
}

impl PhosphorWeight {
    /// Asset directory under `phosphor/` for this weight.
    pub fn dir(self) -> &'static str {
        match self {
            Self::Regular => "regular",
            Self::Bold => "bold",
            Self::Fill => "fill",
        }
    }

    /// Asset path for `icon` at this weight.
    pub fn path(self, icon: PhosphorIcon) -> SharedString {
        format!("phosphor/{}/{}.svg", self.dir(), icon.name()).into()
    }
}

/// A weight-aware Phosphor icon that inherits the surrounding text style
/// (size and color) unless overridden.
#[derive(IntoElement)]
pub struct Phosphor {
    icon: PhosphorIcon,
    weight: PhosphorWeight,
    size: Option<Pixels>,
    color: Option<Hsla>,
}

impl Phosphor {
    pub fn new(icon: PhosphorIcon) -> Self {
        Self {
            icon,
            weight: PhosphorWeight::default(),
            size: None,
            color: None,
        }
    }

    /// Stroke/fill weight (asset prefix); defaults to [`PhosphorWeight::Regular`].
    pub fn weight(mut self, weight: PhosphorWeight) -> Self {
        self.weight = weight;
        self
    }

    /// Explicit pixel size; defaults to the surrounding text size.
    pub fn size(mut self, size: impl Into<Pixels>) -> Self {
        self.size = Some(size.into());
        self
    }

    /// Explicit color; defaults to the surrounding text color.
    pub fn color(mut self, color: impl Into<Hsla>) -> Self {
        self.color = Some(color.into());
        self
    }
}

impl RenderOnce for Phosphor {
    fn render(self, window: &mut Window, _: &mut App) -> impl IntoElement {
        let text_style = window.text_style();
        let size = self
            .size
            .unwrap_or_else(|| text_style.font_size.to_pixels(window.rem_size()));
        let color = self.color.unwrap_or(text_style.color);
        Icon::default()
            .path(self.weight.path(self.icon))
            .with_size(size)
            .text_color(color)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn count_matches_all() {
        assert_eq!(PhosphorIcon::ALL.len(), PhosphorIcon::COUNT);
        assert!(PhosphorIcon::COUNT > 1_000);
    }

    #[test]
    fn names_are_unique_kebab_stems() {
        let mut seen = std::collections::BTreeSet::new();
        for icon in PhosphorIcon::ALL {
            let name = icon.name();
            assert!(!name.is_empty());
            assert!(name.chars().all(|c| c.is_ascii_lowercase() || c == '-'));
            assert!(seen.insert(name), "duplicate name: {name}");
        }
    }

    #[test]
    fn default_weight_is_regular_via_icon_named() {
        use gpui_kit::assets::IconNamed as _;
        assert_eq!(
            PhosphorIcon::Heart.path().as_ref(),
            "phosphor/regular/heart.svg"
        );
    }

    #[test]
    fn weight_paths_use_the_weight_directory() {
        assert_eq!(
            PhosphorWeight::Regular
                .path(PhosphorIcon::PaperPlaneTilt)
                .as_ref(),
            "phosphor/regular/paper-plane-tilt.svg"
        );
        assert_eq!(
            PhosphorWeight::Bold
                .path(PhosphorIcon::PaperPlaneTilt)
                .as_ref(),
            "phosphor/bold/paper-plane-tilt.svg"
        );
        assert_eq!(
            PhosphorWeight::Fill
                .path(PhosphorIcon::PaperPlaneTilt)
                .as_ref(),
            "phosphor/fill/paper-plane-tilt.svg"
        );
    }
}
